# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Box.Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='e_mail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Box.Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Box.Telephone'),
        ),
    ]
