# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_auto_20170605_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('1', 'Home Number'), ('2', 'Work Number')], default=1, max_length=32),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='type',
            field=models.CharField(choices=[('1', 'Home Number'), ('2', 'Work Number')], default=1, max_length=32),
        ),
    ]
