# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0003_auto_20170606_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('1', 'Home Email'), ('2', 'Work Email')], default=1, max_length=32),
        ),
    ]
